# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vyGQcgfPpon85dfxJwbVoAiDv3Qk3mHP
"""

import pandas as pd

data=pd.read_csv('/content/vertebrate.csv',header='infer')

data

data.info()

data.head()

data.tail()

data.tail(2)

data.head(7)

data.sample()

data.sample(6)

data['Class']

data['Class']=data['Class'].replace(["reptiles","fishes","amphibians","birds"],"non-mammal")

pd.crosstab([data['Warm-blooded'],data['Gives Birth']],data['Class'])

from sklearn import tree

y=data['Class']

y

X=data.drop(['Name','Class'],axis=1)

X

clf=tree.DecisionTreeClassifier(criterion='entropy',max_depth=3)

clf

clf=clf.fit(X,y)

clf

import pydotplus

from IPython.display import Image

dot_data=tree.export_graphviz(clf,feature_names=X.columns,class_names=('mammals','non-mammals'),filled=True,out_file=None)

graph=pydotplus.graph_from_dot_data(dot_data)

Image(graph.create_png())